### ISSUE TITLE
Visual Studio 2017编译报错

### ISSUE THREAD

**Issue by ghost** [Richasy/Richasy-Controls-UWP#1]
大佬您好，在编译样例App的时候报错了。
报错内容:
```
错误	CS8306	推断出元组元素名称“Tag”。请使用语言版本 7.1 或更高版本按推断名称访问元素
```
![image](https://user-images.githubusercontent.com/74648104/101127467-9a50ff00-3638-11eb-842c-b717a38404a0.png)
![image](https://user-images.githubusercontent.com/74648104/101127487-a63cc100-3638-11eb-8a75-b6d6a824d156.png)

**Comment by Richasy** [comment]
请在1809及以上的Windows10系统中使用Visual Studio 2019运行该项目，在运行前确保所需SDK都已正确安装

**Comment by ghost** [comment]
谢谢大佬
